apiVersion: v1
kind: ConfigMap
metadata:
  name: machinery-service
data:
  application.properties: |-
    quarkus.log.level=INFO
    quarkus.log.category."io.qiot.manufacturing".level=INFO
    qiot.machinery.serial=abattaglmachinery
    qiot.machinery.name=abattaglmachinery
    facility-manager-api/mp-rest/url=https://facility-manager-service-factory.apps.manufacturingfacility.qiot.io
    qiot.artemis.sslEnabled=true
    qiot.artemis.host=broker-service-edge-0-svc-rte-factory.apps.manufacturingfacility.qiot.io
    qiot.artemis.port=443
